### ISSUE TITLE
Problema no acesso aos serviços do docker

### ISSUE THREAD

**Issue by rolivegab** [nossas/bonde-install#18]
### Contexto

O bonde-install foi feito de forma que os serviços compartilhem a rede através de subnets, simulando realmente a ideia de microserviços que se comunicam entre si e trazendo o ambiente para algo mais próximo do mundo real. Essa configuração também diminui a chance de que conflitos aconteçam entre os serviços do bonde e outros serviços existentes na máquina host.

Entretanto, por algum motivo, algumas vezes isso não funciona, e o serviços ficam indisponíveis para serem acessados tanto pelo host, quanto pelo IP.

### Exemplo

Após instalar, configurar e subir o sistema, ao tentar acessar um determinado serviço, dá um problema de DNS e a conexão é resetada.

![image](https://user-images.githubusercontent.com/7359906/57824988-55722880-7773-11e9-80b7-8ba4013a24a4.png)

No entanto, ao subir o ambiente retirando o mapeamento em endereços de subnet na configuração de cada um dos containers, o acesso aos serviços funciona normalmente.

### Requisitos e Critérios de Aceite

- [ ] Se possível, identificar o que ocasiona esse problema de rede, e resolvê-lo.
- [ ] Caso não seja possível identificar o motivo do problema, remover a organização de containers por endereços de subnet e fazer com que o sistema rode localmente como um todo, de forma que a nova estrutura proposta não cause nenhuma consequência tangível ao processo de desenvolvimento como um todo.

**Comment by lpirola** [comment]
Se puder abrir o PR com o código que remove a rede, pode ser uma solução
