### ISSUE TITLE
Development environment

### ISSUE THREAD

**Issue by rolivegab** [nossas/bonde-install#21]
### Context

Today, when comes up the need to configure development environment to work with chat-bot, it becomes necessary to do various steps manually which ends up disrupting the process.

It would be much easier if the chat-bot setup process was automatic and was part of the bonde-install configuration scripts.

### Requirements

- [ ] run migrate command on api-v3 as part of install process.
- [ ] insert configuration command for chatbot created on `Makefile` file.

**Comment by lpirola** [comment]
Com a nova organização dos módulos será desnecessário essa etapa
