### ISSUE TITLE
make migrate command is not working

### ISSUE THREAD

**Issue by igr-santos** [nossas/bonde-install#4]
I'm trying to run the `make migrate` command, but I get the following error:

```
ERROR: No container found for pgmaster_1
Makefile:40: recipe for target 'migrate' failed
make: *** [migrate] Error 1
```

**Comment by igr-santos** [comment]
trying to follow the commands in `Makefile`, I realized that the pgpool and pgmaster services do not stay online.

*pgpool log output:*

```
pgpool_1 | >>> STARTING SSH (if required) ...
pgpool_1 | cp: can not stat '/home/postgres/.ssh/keys/*': No such file or directory
pgpool_1 | No pre-populated ssh keys!
pgpool_1 | >>> TUNING UP SSH CLIENT ...
pgpool_1 | >>> There are no ssh keys - SSH daemon can not be enabled!
pgpool_1 | >>> STARTING SSH (if required) ...
pgpool_1 | cp: can not stat '/home/postgres/.ssh/keys/*': No such file or directory
pgpool_1 | No pre-populated ssh keys!
pgpool_1 | >>> TUNING UP SSH CLIENT ...
pgpool_1 | >>> There are no ssh keys - SSH daemon can not be enabled!
```

*pgmaster log output:*

```
pgmaster_1       | >>> Setting up STOP handlers...
pgmaster_1       | >>> STARTING SSH (if required)...
pgmaster_1       | cp: cannot stat '/home/postgres/.ssh/keys/*': No such file or directory
pgmaster_1       | No pre-populated ssh keys!
pgmaster_1       | >>> TUNING UP SSH CLIENT...
pgmaster_1       | >>>  There are no ssh keys - SSH daemon can not be enabled!
pgmaster_1       | >>> Setting up STOP handlers...
pgmaster_1       | >>> STARTING SSH (if required)...
pgmaster_1       | cp: cannot stat '/home/postgres/.ssh/keys/*': No such file or directory
pgmaster_1       | No pre-populated ssh keys!
pgmaster_1       | >>> TUNING UP SSH CLIENT...
pgmaster_1       | >>>  There are no ssh keys - SSH daemon can not be enabled!
```

**Comment by lpirola** [comment]
Se esse erro aparecer:

```
psql: could not connect to server: No such file or directory
        Is the server running locally and accepting
        connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
make: *** [migrate] Error 2
```

tente executar o comando ```make migrate``` novamente.

**Comment by lpirola** [comment]
@hudsama os serviços de domínio e notificação estão subindo mas eles tem dificuldades em conectar com o pgpool, muitas vezes o hostname não é reconhecido. Consegue testar por aí e ver se acontece a mesma coisa? Talvez seja uma possibilidade usar ip fixo mas não era o que gostaria.

**Comment by hudsama** [comment]
@lpirola vou atualizar meu repo e testar logo mais. Assim que tiver um parecer te informo como foi meus tests.

**Comment by hudsama** [comment]
@lpirola o problema no `make migrate` parou. Ele rodou lindamente aqui. 
Tive problemas ao subir a app. Veja os logs. Rodei o `make begin` após o `make migrate`


![screen shot 2018-07-09 at 09 47 46](https://user-images.githubusercontent.com/6902011/42451393-7b732abc-835d-11e8-946c-72648e9028e9.png)
![screen shot 2018-07-09 at 09 48 13](https://user-images.githubusercontent.com/6902011/42451394-7b9d1cc8-835d-11e8-84f5-0d64c81c68e5.png)

**Comment by lpirola** [comment]
@hudsama pode rodar "make restart" e ver se o log para de dar esse erro? Você consegue conectar no postgres depois de rodar o "make begin"?

**Comment by igr-santos** [comment]
closed on pull-request https://github.com/nossas/bonde-install/pull/5
