### ISSUE TITLE
how to management images for any services individually

### ISSUE THREAD

**Issue by igr-santos** [nossas/bonde-install#6]
## Objetivo
Documentar o processo para gerenciar versionamento das imagens usadas por serviço (docker-compose), com intuito de criar um comando no `Makefile` para facilitar execução no ambiente de desenvolvimento.

## Caso de uso

*Estou no ambiente de desenvolvimento e quero testar uma `feature-branch` para me certificar que a integração entre os serviços estão acontecendo como devem*

**Comment by lpirola** [comment]
com a nova arquitetura de módulos, não será mais necessário
